# Generated by Django 2.0 on 2019-09-20 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190920_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='fristname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='fristname',
            new_name='firstname',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
